export const enum Scope {
	HOSTED_READ = 'HOSTED_READ',
	HOSTED_WRITE = 'HOSTED_WRITE',
	USERS_READ = 'USERS_READ',
	USERS_WRITE = 'USERS_WRITE',
	PANELS_READ = 'PANELS_READ',
	PANELS_WRITE = 'PANELS_WRITE',
	SCHEDULE_READ = 'SCHEDULE_READ',
	SCHEDULE_WRITE = 'SCHEDULE_WRITE',
}
